# Generated by Django 5.1.5 on 2025-01-28 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(default='Deleted account', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='send_messages', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(default='Deleted account', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
