# Generated by Django 5.1.5 on 2025-02-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_is_delivery_chatmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='is_delivery',
            field=models.DateTimeField(default=False),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
