# Generated by Django 5.1.5 on 2025-02-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_groupmessage_is_delivery_groupmessage_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
